[project]
name = "md2json"
version = "0.0.0"
authors= [
  {name = "CHIPS Alliance Authors"}
]
dependencies = [
  "mistletoe>=1",
  "requests>=2",
]

[project.scripts]
md2json = "md2json.md2json:main"
